image: docker:latest
services:
  - docker:dind
variables:
  REGISTRY_URL: https://${DOCKER_REGISTRY}
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  DOCKER_DRIVER: overlay2

stages:
  - build

build:
  stage: build
  tags:
    - docker
  before_script:
    - apk add --no-cache git # Install Git
    - docker login --username ${DOCKER_USER} --password ${TOKEN} cr.yandex
  script:
    - docker build -t ${REGISTRY_URL}/${PROJECT_NAME}:${IMAGE_TAG} .
    - docker push ${DOCKER_REGISTRY}/${PROJECT_NAME}:${IMAGE_TAG}