image: docker:latest
services:
  - docker:dind
variables:
  REGISTRY_URL: https://${DOCKER_REGISTRY}
  IMAGE: ${DOCKER_REGISTRY}/${PROJECT_NAME}:001
  RELEASE: ${DOCKER_REGISTRY}/${PROJECT_NAME}:latest
  IMAGE_TAG: 001
  DOCKER_DRIVER: overlay2

stages:
  - build

build:
  stage: build
  tags:
    - docker
  before_script:
    - apk add --no-cache git # Install Git
    - docker login --username ${DOCKER_USER} --password ${TOKEN} cr.yandex
  script:
    - docker build -t ${IMAGE} .
    - docker push ${DOCKER_REGISTRY}/${PROJECT_NAME}:${IMAGE_TAG}